server: 
    port: 8080
cors:
  allowed-methods:
    - OPTIONS
    - GET
    - PUT
    - POST
    - PATCH
    - DELETE
  allowed-headers:
    - Accept
    - Authorization
    - Content-Type
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Methods
    - Access-Control-Allow-Headers
    - Access-Control-Expose-Headers
  exposed-headers:
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Expose-Headers
    - Content-Type
    - Authorization
    - Accept
  allow-credentials: true
  allowed-origins: 
    - http://localhost:3000
spring:
    application:
        name: mealplanner
    jpa:
        hibernate:
            ddl-auto: create-drop
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    datasource:
        url: jdbc:h2:mem:mealplanner
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console.enabled: true
okta:
    oauth2:
        issuer: https://dev-rtcs71fqxvr68wkj.us.auth0.com/
        audience: https://whiskerandwhisk/api